spectaql:
  embeddable: true
  oneFile: true
  targetDir: /Users/bolajio/Developer/docs/test
  # themeDir: ./doc/_resources/spectaql/


introspection:
  # the order of these files are important because spectaql cant infer the types and 
  # query extended from schema.graphql or any other files before hand
  schemaFile: 
    - ../sourcegraph/cmd/frontend/graphqlbackend/schema.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/githubapps.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/batches.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/codeintel.autoindexing.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/codeintel.policies.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/codeintel.ranking.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/codeintel.sentinel.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/cody_context.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/completions.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/compute.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/content_library.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/dotcom.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/embeddings.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/guardrails.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/insights.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/insights_aggregations.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/license.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/notebooks.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/outbound_webhooks.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/own.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/rbac.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/search_contexts.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/search_jobs.graphql
    - ../sourcegraph/cmd/frontend/graphqlbackend/telemetry.graphql

  # Whether to document any Queries at all, in the absence of a metadata directive
  # Default: true
  queriesDocumentedDefault: true
  # Whether to document an individual Query, in the absence of a metadata directive
  # Default: true
  queryDocumentedDefault: true
  # Whether to document a Query Argument, in the absence of a metadata directive
  # Default: true
  queryArgDocumentedDefault: true
  # Hide any Queries with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideQueriesWithUndocumentedReturnType: true

  # Whether to document any Mutations at all, in the absence of a metadata directive
  # Default: true
  mutationsDocumentedDefault: true
  # Whether to document an individual Mutation, in the absence of a metadata directive
  # Default: true
  mutationDocumentedDefault: true
  # Whether to document a Mutation Argument, in the absence of a metadata directive
  # Default: true
  mutationArgDocumentedDefault: true
  # Hide any Mutations with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideMutationsWithUndocumentedReturnType: true

  # Whether to document any Types at all
  # Default: true
  typesDocumented: true
  # Whether to document an individual Type, in the absence of a metadata directive
  # Default: true
  typeDocumentedDefault: true
  # Whether to document an individual Field, in the absence of a metadata directive
  # Default: true
  fieldDocumentedDefault: true
  # Whether to document an individual Argument, in the absence of a metadata directive
  # Default: true
  argDocumentedDefault: true
  # Hide any fields with undocumented return types so as not to reference something
  # that seemingly does not exist.
  # Default: true
  hideFieldsWithUndocumentedReturnType: true

  #
  #
  ##############################################

servers:
  - url: https://sourcegraph.com/.api/graphql
    description: sourcegraph.com
    production: true

info:
  # Set to true to do no Introduction area rendering at all. Supersedes the below options
  # Default: false
  x-hideIntroduction: true
  # Set to true to not render a friendly Welcome section based on the description in this area
  # Default: false
  x-hideWelcome: true
  # Set to true to not render your intro items
  # Default: false
  x-hideIntroItems: true


  # Set to true to not render the deprecated label
  # Default: false
  x-hideIsDeprecated: false
  # Set to true to not render the deprecation reason
  # Default: false
  x-hideDeprecationReason: false

  #
  ##############################################

  # A non-standard array of items to display in your Introduction Area
  x-introItems:
    - title: sourcegraph.com
      url: https://sourcegraph.com
    - title: API console
      url: https://sourcegraph.com/api/console

  description: Sourcegraph API
  version: 1.0.0
  title: Sourcegraph API
  termsOfService: 'https://about.sourcegraph.com/terms'
  contact:
    name: Sourcegraph Support
    email: support@sourcegraph.com
    url: https://about.sourcegraph.com/
  license:
    name: Apache + Enteprise
    url: 'https://github.com/sourcegraph/sourcegraph/blob/main/LICENSE'


